[package]
name = "node-rust"
version = "0.1.0"
authors = ["Simon Bugge Siggaard <buggaarde@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.8.6"
pb-jelly = "0.0.5"
