[package]
name = "node-rust"
version = "0.1.0"
authors = ["Simon Bugge Siggaard <buggaarde@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-nats = "0.9.7"
async-trait = "0.1.50"
smol = "1.2.5"
